name: Build and Push BC Tenant Docker Image to GHCR

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/bc-tenant-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/bc-tenant-app:latest

  deploy-develop:
    needs: build-and-push
    runs-on: ubuntu-latest
    # Condition: Only run this job when the push is to the 'main' branch
    if: github.ref == 'refs/heads/develop'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Deploy to SSH Server - Develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/bc_main/black-country-tenant-test/
            sudo git pull
            cd ..
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose up -d tenant
            echo "Dev image deployed and running..."
            docker system prune --force
            echo "Cleanup complete"

  deploy-prod:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Deploy to SSH Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            cd ~/black-country-tenant-test/
            sudo git pull
            cd ..
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose up -d tenant
            echo "Prod image deployed and running..."
            docker system prune --force
            echo "Cleanup complete"
            